server.port=8083
spring.application.name=audit-service

# Konfiguracja MongoDB (zgodna z Twoim docker-compose)
spring.data.mongodb.uri=mongodb://localhost:27017/audit_db

# Konfiguracja RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672