[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"

[[inputs.docker]]
  endpoint = "tcp://host.docker.internal:2375"
  timeout = "5s"
  perdevice = false

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  metric_version = 2
